jetty:
  httpPort: 80
  httpsPort: 8080
  keyStore: classpath:keystore
  passWord: hydt2017


debug: true

security:
  basic:
    enabled: false
  user:
    name: hy9902
    password: vgundam0097
  oauth2:
      client:
        clientId: 233668646673605
        clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
        accessTokenUri: https://graph.facebook.com/oauth/access_token
        userAuthorizationUri: https://www.facebook.com/dialog/oauth
        tokenName: oauth_token
        authenticationScheme: query
        clientAuthenticationScheme: form
      resource:
        userInfoUri: https://graph.facebook.com/me

management:
  security:
    roles: SUPERUSER
    enabled: false

#spring
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:/db/schema-h2.sql
    data: classpath:/db/data-h2.sql
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    platform: h2
    initialize: true
    continue-on-error: true
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /console

  session:
    store-type: none

  #output log color
  output:
    ansi:
      enabled: always

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 120MB
    encoding:
      charset: UTF-8
      enabled: true
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    dispatch-options-request: false
    dispatch-trace-request: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  messages:
    basename: i18n/messages, i18n/my
    encoding: UTF-8

#rabbitmq
#  rabbitmq:
#    host: 192.168.201.62
#    port: 5672
#    username: ds
#    password: ds
#    virtual-host: dsdemoHost
#    listener:
#      simple:
#        acknowledge-mode: auto
#        max-concurrency: 20
#    cache:
#      channel:
#        size: 20
#
#  redis:
#    host: localhost
#    port: 6379
#    password: ds2017@szedi.cn


logging:
  level:
    com.hydt: debug

dc:
  enable: true
  eir:
    apl: 美国总统
    cma: 达飞轮船
    a b: c
  pc:
    - mac
    - thinkpad
    - sony
    - xiaomi
#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: classpath:keystore
#    key-password: hydt2017


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hydt.app.vo
  typeEnumsPackage: com.hydt.app.vo.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
